#!/usr/bin/env bash
# Check if number of arguments is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# Transfer the file using scp
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$ubuntu@54.158.193.5":~

# Check if scp command succeeded
if [ $? -eq 0 ]; then
    echo "File transferred successfully"
else
    echo "Failed to transfer file"
fi
