#!/usr/bin/env bash
# This script configures Nginx to add a custom HTTP header on a new Ubuntu machine

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Add custom header configuration to Nginx
sudo sed -i '/298037-lb-01;/a \        add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Restart Nginx
sudo systemctl restart nginx
