#!/usr/bin/env bash
# Script to configure Nginx to return "Hello Holberton"

# Update Nginx default configuration to return "Hello Holberton"
echo "server {
    listen 80;
    listen [::]:80;

    server_name _;

    location / {
        return 200 'Hello Holberton\n';
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx to apply the configuration changes
service nginx restart
