#!/usr/bin/env bash
# Configure Nginx to return "Hello Holberton" on port 80

echo "server {
    listen 80;
    listen [::]:80;

    server_name _;

    location / {
        return 200 'Hello Holberton\n';
    }
}" > /etc/nginx/sites-available/default

service nginx restart
