#!/usr/bin/env bash
# This script displays "Best School" 10 times using a while loop

# Counter variable
count=0

# Using a while loop to display "Best School" 10 times
while [ $count -lt 10 ]; do
    echo "Best School"
    ((count++))
done
