#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

# Counter variables for hours and minutes
hour=0
minute=1

# Using a while loop to iterate over hours
while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    
    # Using a nested while loop to iterate over minutes
    while [ $minute -le 59 ]; do
        echo "$minute"
        ((minute++))
    done
    
    # Reset minute counter for the next hour
    minute=1
    
    ((hour++))
done
